### ISSUE TITLE
Allow more complex labels to be defined

### ISSUE THREAD

**Issue by reececomo** [kaxil/boring-cyborg#16]
Currently only basic label config is supported:
```yaml
labelPRBasedOnFilePath:
  schema:
    - database/migrations/*
```

Supporting more advance options (specifically `color` and `description`) would add a lot of power to the tool (particularly if combined with https://github.com/kaxil/boring-cyborg/issues/15)

### Example: 
```yaml
labelPRBasedOnFilePath:
  - label: schema
    files: ['database/migrations/*']

  - label: 'legacy/models :fire:'
    color: '#f04411'
    description: 'Warning: This PR touches the legacy data models.'
    files:
      - lib/models/*
      - lib/models/**/*
```

**Comment by reececomo** [comment]
(This would, in the future, allow us to add labels based on other triggers too)

e.g.

```yaml
autolabel:
  - label: schema
    files: ['database/migrations/*']

  - label: 'Cool Project'
    files: ['app/CoolProject/**', 'app/CoolProject/*']
    titleRegex: '.*COOL\-.*'
```
