### ISSUE TITLE
Automatically add a label when an Issue/PR is created

### ISSUE THREAD

**Issue by CompeyDev** [kaxil/boring-cyborg#45]
Is there a way to automatically add a label when an issue/PR is created? For example, by making the trigger the root directory (for example, using `*` in the config).

**Comment by kaxil** [comment]
Yeah it should work if you use:

```yaml
labelPRBasedOnFilePath:
  label1:
    - "**"
```
